### ISSUE TITLE
Automate wrapping of Metric types

### ISSUE THREAD

**Issue by flora-hofmann-frequenz** [frequenz-floss/frequenz-api-reporting#15]
Currently, each metric in `_types.py` in PR #14 is transformed as follows: 
`AC_FREQUENCY = metric_sample_pb2.Metric.METRIC_AC_FREQUENCY`

Can we automate this based on the .proto files so it is less verbose?

**Comment by cwasicki** [comment]
For now we won't look into this as. This might also be less of an issue if we switch to betterproto.
