### ISSUE TITLE
Add feature to filter data by metric source

### ISSUE THREAD

**Issue by tiyash-basu-frequenz** [frequenz-floss/frequenz-api-reporting#44]
### What's needed?

[Metric sources](https://github.com/frequenz-floss/frequenz-api-common/blob/b354ac4aa7b268161d0faffdce9d1915fe6034f1/proto/frequenz/api/common/v1/metrics/metric_sample.proto#L211-L225) are additional tags on metrics that can be used to specify which source (within a component) they come from. E.g., for inverters with multiple DC strings, we represent each string as a source, and each source will have DC metrics of its own.

Currently, when making requests to fetch data from the Reporting API, there is no way to specify which metric `source` to look for. Having a filter like this could be useful, as this might help narrow down requests only to a specific set of sources at a time.

### Proposed solution

Here is a proposal that extends the [`StreamFilter` message](https://github.com/frequenz-floss/frequenz-api-reporting/blob/5e033bd49357af126e6ed62782a8f910b6cf6be4/proto/frequenz/api/reporting/v1/reporting.proto#L304-L315) :

```proto
// Filter for sources for metrics, specified for a single metric at a time.
message MetricSourceOptions {
    // The metric for which sources will be filtered in.
    Metric metric = 1;

    // A list of sources to allow for the specified metric.
    // If this list is empty, then no data for this metric is streamed.
    repeated string metric_sources = 2;
}

message StreamFilter {
    ...

    // Filter for metric sources.
    repeated MetricSourceOptions metric_source_options = 4;
}
```

### Use cases

This could be used to narrow down filters for components which expose a metric for several sources at a time.

**Comment by cwasicki** [comment]
>    // If this list is empty, then no data for this metric is streamed.

Would there also be a way to stream all sources without specifying them?

**Comment by cwasicki** [comment]
>Would there also be a way to stream all sources without specifying them?

In fact I wonder whether this should actually be the result when an empty list is specified. Because why would you request that metric otherwise?

**Comment by tiyash-basu-frequenz** [comment]
> > Would there also be a way to stream all sources without specifying them?
> 
> In fact I wonder whether this should actually be the result when an empty list is specified. Because why would you request that metric otherwise?

This was written this way for consistency, while allowing users to fetch all sources at once. It is consistent because we do the same for metrics - if the metrics list is empty, then no data is returned. Similarly, if the sources list is empty, then no data is returned for the concerned metric. Also, users can get data for a metric from all sources just by not having a filter for that metric.

I assumed that was clear by the design, but it is aparently not. We should then document this more clearly in the PR. FYI @stefan-brus-frequenz .
