### ISSUE TITLE
Remove `states` parameter from `IncludeOptions`

### ISSUE THREAD

**Issue by stefan-brus-frequenz** [frequenz-floss/frequenz-api-reporting#48]
### What's needed?

The reporting API should not be responsible for exposing component states.

### Proposed solution

The `states` field of `IncludeOptions` should be removed.

**Comment by cwasicki** [comment]
The requirements have changed and we have to keep this option. At least for now, whether we can remove it at all needs to be decided at a later stage.

**Comment by stefan-brus-frequenz** [comment]
Closing this
